### ISSUE TITLE
npm link @umbraco/playwright-testhelpers

### ISSUE THREAD

**Issue by hannakfoo** [umbraco/Umbraco.Playwright.Testhelpers#15]
Hi 👋 currently giving this project a try! And I am having fun with playwright. But I encounter the following issue: 

In the README file the instruction is given to run `npm run build` & `npm link` in the root of the folder. After that you link the newly build package by run `npm link @umbraco/playwright-testhelpers` in the project where you are using the package. 

This all seems to work but after running the AcceptanceTest project against the newly linked package I am getting the following error:

```
Running 0 tests using 0 workers
Error: Requiring @playwright/test second time, 
First:
Error:

   at ..\node_modules\@playwright\test\lib\index.js:75

  73 |   }
  74 | } else {
> 75 |   process['__pw_initiator__'] = new Error().stack;
     |                                 ^
  76 | }
  77 |
  78 | const test = _baseTest.extend({

    at Object.<anonymous> (C:\Source\Umbraco-CMS\tests\Umbraco.Tests.AcceptanceTest\node_modules\@playwright\test\lib\index.js:75:33)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.t.<computed>.tu._extensions.<computed> [as .js] (C:\Source\Umbraco-CMS\tests\Umbraco.Tests.AcceptanceTest\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at Object.<anonymous> (C:\Source\Umbraco.Playwright.Testhelpers\lib\helpers\ApiHelpers.ts:5:1)
    at Object.<anonymous> (C:\Source\Umbraco.Playwright.Testhelpers\dist\lib\helpers\index.js:17:20)
    at Object.<anonymous> (C:\Source\Umbraco.Playwright.Testhelpers\dist\lib\index.js:9:22)
    at Object.<anonymous> (C:\Source\Umbraco-CMS\tests\Umbraco.Tests.AcceptanceTest\tests\DefaultConfig\Test\Testing.spec.ts:3:30)
=================
 no tests found.
=================
```

## Workaround
I currently using the following workaround by running `npm pack `in the root of the folder. And copying the generated `umbraco-playwright-testhelpers-1.0.5.tgz` to the project where I am using it (AcceptanceTest for example) and referencing the package in the `package.json` file like this:

```
...
"dependencies": {
    "@umbraco/json-models-builders": "^1.0.0",
    "@umbraco/playwright-testhelpers": "umbraco-playwright-testhelpers-1.0.5.tgz",
    "camelize": "^1.0.0",
    "faker": "^4.1.0",
...
```
This gives no problems or error messages but is a little bit of task intensive.

**Comment by Zeegaan** [comment]
Hey @hannakfoo, yea we've run into this error aswell :( And it seems like playwright has taken a stance that says you should use `npm pack` & `npm -i [output file].tgz`, here is the issue thread from the playwright repository: https://github.com/microsoft/playwright/issues/15819

As this is an official stance from playwright, there's sadly not much we can do about it :(

I will close this issue, but make sure we get the READ.ME updated ASAP! Thanks for reporting 👍

**Comment by Zeegaan** [comment]
Readme updated here: https://github.com/umbraco/Umbraco.Playwright.Testhelpers/pull/17
